# Site settings
title: TJB Synergy
email: info@tjbsynergy.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wwww.tjbsynergy.com" # the base hostname & protocol for your site

linkedin_username:
facebook_username:

# Build settings
markdown: kramdown
